# mkdocs.yml
site_name: Project FoodS - Veilig Irrigatiewater
site_author: Stijn Peeters
site_url: https://<jouw-project>.readthedocs.io/

repo_url: [https://github.com/microstijn/foodS](https://github.com/microstijn/foodS)
repo_name: microstijn/foodS
edit_uri: edit/main/docs/

theme:
  name: material
  language: nl
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - mermaid

# Navigatiestructuur van je website
nav:
  - 'Introductie': 'index.md'
  - 'Belangrijke Begrippen': 'begrippen.md'
  - 'De Risicoâ€™s': 'risicos.md'
  - 'Actieplan & Flowcharts': 'actieplan.md'
  - 'Ziekteverwekkers': 'ziekteverwekkers.md'
  - 'Structurele Maatregelen': 'maatregelen.md'

# Markdown extensies
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format